name: example
description: Example app demonstrating Zuraffa.

publish_to: none

version: 3.10.0

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  zuraffa:
    path: ../
  zorphy_annotation: ^1.5.8
  build_runner: ^2.11.0
  hive_ce_flutter: ^2.3.4
  json_serializable: ^6.12.0
  get_it: ^8.0.0
  json_annotation: ^4.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  mocktail: ^1.0.4
  hive_ce_generator: ^1.11.1

flutter:
  uses-material-design: true

dependency_overrides:
  meta: ^1.18.0
  test_api: ^0.7.9
