name: example
description: Example app demonstrating Zuraffa.

publish_to: none

version: 2.3.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  zuraffa:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  mocktail: ^1.0.4

flutter:
  uses-material-design: true

dependency_overrides:
  meta: ^1.18.0
  test_api: ^0.7.9
