name: zuraffa
description: AI first Flutter Clean Architecture Framework and CLI with Result types, UseCase patterns, Dependency Injection and MCP server for building type-safe, scalable apps with AI agents.
version: 1.8.0
homepage: https://zuraffa.com
repository: https://github.com/arrrrny/zuraffa
issue_tracker: https://github.com/arrrrny/zuraffa/issues
documentation: https://github.com/arrrrny/zuraffa#readme

topics:
  - clean-architecture
  - state-management
  - dependency-injection
  - architecture
  - mvp

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  args: ^2.7.0
  logging: ^1.3.0
  meta: ^1.12.0
  path: ^1.9.0
  provider: ^6.1.5+1
  responsive_builder: ^0.7.1

executables:
  zuraffa:
  zfa:
  zuraffa_mcp_server:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mocktail: ^1.0.4
